# Numpy

Numerisk Python
- Arrays (fält)
- Lik listor
- Matematiska operationer på arrays
- Modellera vektorer och matriser

In [8]:
import numpy as np

array1 = np.array([1,2,3,4])

lista1 = [1,2,3,4]

print(f"Array: {array1}")
print(f"Lista: {lista1}")

# indexera arrays, fungerar på samma sätt som att indexera listor []
print(array1[2])

# multiplicera alla tal med 2
array2 = array1*2
print(array2)

lista2 = lista1*2
print(lista2)

kvadrater = array1**2
print(kvadrater)


Array: [1 2 3 4]
Lista: [1, 2, 3, 4]
3
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 1  4  9 16]


## Användbara numpy-funktioner
- zeros
- ones
- arange
- linspace
- matematiska funktioner och konstanter: pi, sqrt  

In [13]:
import numpy as np

# arange
tal = np.arange(10)
print(tal)
# sqrt
print(np.sqrt(tal))

nollor = np.zeros(6)
print(nollor)

ettor = np.ones(6)
print(ettor)


[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


### Simulera tärningskast

In [17]:
import numpy as np 
import random as rnd

# array med nollor för att preallokera minne
utfall = np.zeros(6, dtype=int)
print(utfall)

antal_kast = 100000
for i in range(antal_kast):
    kast = rnd.randint(1,6)
    utfall[kast-1] += 1

print(f"Tärningskast: {utfall}")
print(f"Sannolikhet: {utfall/antal_kast}")



[0 0 0 0 0 0]
Tärningskast: [16586 16651 16670 16700 16722 16671]
Sannolikhet: [0.16586 0.16651 0.1667  0.167   0.16722 0.16671]
